import Navber from "@/components/navbar/Navber";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { Providers } from "./ReduxGlobal/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lipon Roy App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navber />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
